### ISSUE TITLE
Future Request: Add an image to base image.

### ISSUE THREAD

**Issue by Hadi7546** [haashemi/writer#1]
First of all, thank you for this beautiful project. I am going to add an image (logo) to the main and base image for a design (similar to adding a sticker to a photo). Do you think it is possible to implement something like this? And how can I help you implement it?

**Comment by haashemi** [comment]
Hi! Thanks for the kind words.

Such a thing could be done using the `image/draw` package and is way out of scope of this package.

You can do it yourself with a basic code like this:
```go
// Paste draws the src image on dst image at x,y of the dst.
func Paste(dst *image.NRGBA, src image.Image, x, y int) {
	draw.Draw(dst, src.Bounds().Add(image.Point{x, y}), src, image.Point{}, draw.Over)
}
```

Also, for image processing I recommend you to take a look at these packages:
- [painter](https://github.com/haashemi/painter)
- [imaging](https://github.com/disintegration/imaging)

With that said, this feature is not planned, yet.
